### ISSUE TITLE
Low level debugging tools (GDB, Valgrind)

### ISSUE THREAD

**Issue by voithos** [codio/boxparts#139]
It would be nice if some low level debugging tools were added to the Box Parts repository. Specifically, I was thinking of `gdb` and `valgrind` - extremely useful when you're dealing with an inexplicable segmentation fault.

The existence of GCC and `make` in the Box is very nice - adding some debugging tools would give a nice basis for C and C++ development.

**Comment by hortinstein** [comment]
+1

**Comment by ghost** [comment]
Check out our new G2 boxes where you have sudo access and can install packages using apt 

https://codio.com/docs/ide/boxes/
