### ISSUE TITLE
Box part for a command line ftp client

### ISSUE THREAD

**Issue by landyman** [codio/boxparts#261]
I would like to see ftp, lftp, or anything compatible be available.

I know there is an option for FTP in the deployment settings; but if I only need to deploy one or two files, then the FTP deployment is overkill. Conversely, if someone else makes changes to the server and I need to pull a file or two; having the ftp command line would be very handy.

I would much rather prefer to use git; but not all clients/projects and dev teams use it for all projects.

Thank you.

**Comment by ijobling** [comment]
@landyman 
Git is pre installed but also have you checked out the existing gitftp box part?  Should I think allow you to do what you are asking for here? If not pls re-open

And also if your servers support RSYNC (most nowadays I think do?) that could work as well perhaps

**Comment by landyman** [comment]
Thanks @ijobling. Unfortunately, rsync will not work on this particular client; both it and ssh are disabled. Gitftp also seems like it will not work as I cannot pull changes that others may make to the server files.

Also, github won't let me re-open this issue; can you please re-open it?

Thanks.
