### ISSUE TITLE
Add gdb box part

### ISSUE THREAD

**Issue by kcris** [codio/boxparts#265]
please add a gdb box part (c++ debugger)

**Comment by minh0722** [comment]
+1

**Comment by hortinstein** [comment]
+1

**Comment by ghost** [comment]
Check out our new G2 boxes where you have sudo access and can install packages using apt

https://codio.com/docs/ide/boxes/

**Comment by minh0722** [comment]
I assume gdb is still in review to be added? Because I don't see it in the available packages

**Comment by ghost** [comment]
It won't be added as a box part which is only available for the old boxes.

Look at creating a new box with the new stacks where you have sudo access and can install packages using apt

**Comment by minh0722** [comment]
Nice! Working great! One of a kind online IDE
