### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by godfreynolan** [codio/boxparts#331]
Need the following boxparts added to build Swift
ninja-build 
clang 
libicu-dev 
icu-devtools 
libbsd-dev 
libedit-dev 
libxml2-dev 
swig 
libpython-dev 
libncurses5-dev 
pkg-config

**Comment by ghost** [comment]
@godfreynolan 

Hang on a while, we have something we are working on at the moment that will make all this a lot simpler for you. Can't give you a specific timeline but shouldn't be far off now.  I'll let you know when its available

**Comment by ghost** [comment]
@godfreynolan 
Check out our new G2 boxes where you have sudo access and can install packages using apt 

https://codio.com/docs/ide/boxes/
