### ISSUE TITLE
shutting down with code:100

### ISSUE THREAD

**Issue by drzivkovic** [codio/boxparts#333]
Hi, I am new to MongoDB and started an online course on MongoDB University. I followed the tutorial on how to install MongoDB on Mac and when I try to start MongoDB I get this error: shutting down with code:100
 Can you help me solve this error?
Thank you

**Comment by ghost** [comment]
We no longer support boxparts and do not know what 'tutorial' you refer to here so can't really help but to install MongoDB to a Codio project, just go to Tools>Install Software and MongoDB is available to install there.
Alternatively of course, talk to the people running this course you refer to, they should be able to help

**Comment by drzivkovic** [comment]
Thank you
