### ISSUE TITLE
php5-pdo-mysql doesn't install driver

### ISSUE THREAD

**Issue by nesl247** [codio/boxparts#72]
The driver must not be installed properly because I am getting `Uncaught exception 'PDOException' with message 'could not find driver'`. I performed a `parts install php5 php5-pdo-mysql apache2 mysql`

I've even restarted the box to make sure and it still doesn't work.

**Comment by bituka** [comment]
I think this should be added in the documentation - https://codio.com/docs/ide/tutorials/laravel/
